tinyMCE.addI18n('de.contaolinks_dlg',{
page:"Seite",
file:"Datei",
url:"URL",
email:"E-Mail",
link_title:"Verlinkung einf\u00FCgen/bearbeiten",
page_title:"Seite",
file_title:"Datei",
email_title:"E-Mail",
phone_title:"Telefon",
url_title:"Externe Adresse",
email:"E-Mail Adresse",
email_desc:"Geben Sie hier eine E-Mail Adresse ein: martin@muster.de",
phone:"Telefon- / Faxnummer",
phone_desc:"Geben Sie hier eine Telefonnummer ein: +491234-567890<br/>Die Telefonnumer darf keine mehrdeutigen Element enthalten, z.B. einen doppelten Ländercode: +49 (0), lassen Sie die (0) einfach weg und tragen Sie die International gültige, vollständige Rufnummer ein.<br/>Bitte beachten Sie, das verlinken einer Telefonnummer funktioniert in der Regel nur auf Mobilen Geräten (Smartphones) korrekt. Auf PCs funktioniert die Telefonnummer nur in Verbindung mit einer installierten Telefonsoftware (VOIP / Skype).",
url:"Internet Adresse",
url_desc:"Geben Sie hier eine beliebige Internet Adresse ein: http://www.google.de",
link_url:"Adresse",
link_target:"Fenster",
link_target_same:"Im selben Fenster \u00F6ffnen",
link_target_blank:"Neues Fenster \u00F6ffnen",
link_titlefield:"Titel",
link_is_email:"Bei der Adresse scheint es sich um eine E-Mail-Adresse zu handeln. Wollen Sie das dazu ben\u00F6tigte mailto: voranstellen?",
link_is_external:"Bei der Adresse scheint es sich um einen externen Link zu handeln. M\u00F6chten Sie, dass zur korrekten Verlinkung ein http:// vorangestellt wird?",
link_list:"Linkliste",
image_title:"Vorschaubild einf\u00FCgen/bearbeiten",
image_list:"Bilderliste",
image_src:"Bild-Url",
image_dimensions:"Breite/H\u00F6he",
image_alt:"Beschreibung",
image_class:"CSS-Klasse",
image_resize_mode:"Modus",
image_crop:"Exaktes Format",
image_proportional:"Proportional",
image_box:"An Rahmen anpassen",
image_rel:"Lightbox",
image_rel_single:"Einzelnes Element",
image_rel_multi:"Galerie"
});